[package]
name = "opie"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
dirs = "6.0.0"
futures = "0.3.32"
iced = { version = "0.14.0", features = ["advanced", "tokio"] }
matrix-sdk = { version = "0.16.0", features = ["sso-login", "experimental-search", "anyhow"] }
matrix-sdk-ui = "0.16.0"
screen_macro = { path = "macros/screen_macro" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["rt"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

[features]
debug = ["iced/hot", "iced/time-travel"]
